data:
  train_image_dir: /data/zhelonghuang/datasets/chestxray-14/images
  train_image_label: /data/zhelonghuang/datasets/chestxray-14/Data_Entry_2017.csv
  cache_dir: ./data
  name: chestxray14

model:
  ID_labels: [0, 1, 2, 3, 4]
  OOD_labels: [5, 6]
  focal: 0
  kl: 0

train:
  checkpoint: ''
  batch_size: 256
  lr: 1e-4
  wd: 1e-4
  max_epochs: 50
  save_dir: './runs'